export const UI_COLORS = {
  TOOL: 'cyan',
  TOOL_DESCRIPTION: 'gray',
  TOOL_RESULT: 'gray',
  WARNING: 'yellow',
  ERROR: 'red',
  INFO: 'gray',
  MODE_TEXT: 'cyan',
  MODE_HINT: 'gray',
  ACTIVE: 'green',
  CHAT_BORDER: 'gray',
  CHAT_BORDER_ACTIVE: 'cyan',
  CHAT_BORDER_BASH: 'yellow',
  CHAT_BORDER_MEMORY: 'magenta',
  CHAT_PLACEHOLDER: 'gray',
  CHAT_ARROW: 'gray',
  CHAT_ARROW_ACTIVE: 'white',
  STATUS: 'gray',
  STATUS_ACCENT: 'cyan',
} as const;
